---
- name: Install postgis extensions
  become: yes
  apt: pkg={{ item }}
  with_items:
    - "postgresql-{{ pg_version }}-postgis-{{ pg_postgis_version }}"
    - libgeos-c1
  tags:
    - postgresql
