galaxy_info:
  author: Nick Janetakis
  description: Install and configure nginx (SSL A+ by default).
  company:
  license: license MIT
  min_ansible_version: 2.0

  platforms:
  - name: Ubuntu
    versions:
    - xenial
  - name: Debian
    versions:
    - jessie

  categories:
  - system
  - networking
  - web

dependencies: []
