---
- name: Install prerequisites
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - iptables
    - iptables-persistent

- name: Apply rules
  script: basic_iptables_rules.sh

# - name: Restart iptables-persistent
#   service: name=iptables-persistent state=restarted enabled=yes
