---
  - name: Configure app web server
    hosts: all
    remote_user: "{{ my_user }}"
    become: yes
    vars:
      my_user: stefano
      my_site: gammasense.org
      admin_mail: "{{ my_user }}/@{{ my_site }}"
      root_dir: /var/www
      app_name: gamma
      my_home: "/home/{{ my_user }}"
      git_home: "/home/{{ my_user }}/src/{{ app_name }}"
      git_repo: https://github.com/waagsociety/makingradio.git
      node_version: 6.x
      app_port: 8090
    roles:
     - role: zzet.postgresql
     - role: palkan.ruby
     - role: thefinn93.letsencrypt
       letsencrypt_webroot_path: "{{ root_dir }}"
       letsencrypt_email: "{{ admin_mail }}"
       letsencrypt_cert_domains:
        - "{{ my_site }}"
        - "www.{{ my_site }}"
       letsencrypt_renewal_command_args: '--renew-hook "systemctl restart nginx"'
     - role: nickjj.nginx
       tags: nginx
       # nginx_basic_auth:
       #   - { user: 'coolperson', password: 'heylookatmeicanviewtheprivateblog' }
       nginx_sites:
         default:
           domains: ["{{ my_site }}"]
           default_server: True
           root: "{{ root_dir }}/{{ app_name }}"
           nginx_letsencrypt_root: "{{ root_dir }}/challenges"
           ssl:
             certpath: /etc/letsencrypt/live
           # upstreams:
           #   - name: 'myapp'
           #     servers: ['localhost:3000', 'localhost:3001']
         # blog:
         #   domains: ['blog.example.com']
         #   serve_assets:
         #     enabled: False
         #   basic_auth: True
         www:
            domains: ["www.{{ my_site }}"]
            default_server: False
            root: "{{ root_dir }}/{{ app_name }}"
            nginx_letsencrypt_root: "{{ root_dir }}/challenges"
            ssl:
              certpath: /etc/letsencrypt/live
         app:
             domains: ["{{ my_site }}"]
             listen_http: "{{ app_port }}"
             listen_https: "{{ app_port }}"
             default_server: False
             root: "{{ root_dir }}"
             nginx_letsencrypt_root: "{{ root_dir }}/challenges"
             ssl:
               certpath: /etc/letsencrypt/live
             upstreams:
               - name: 'gammaapp'
                 servers: ['localhost:4000']
                 add_proxy_settings:
                   - 'proxy_http_version 1.1'
                   - 'proxy_set_header Host $http_host'
                   - 'proxy_set_header Upgrade $http_upgrade'
                   - 'proxy_buffering off'
    #  - role: mrlesmithjr.nodejs
    #    nodejs_debian_packages:
    #      - npm
    #      - build-essential
     - role: ChengLong.iptables
    tasks:
      - name: Set Node repo
        script: ./install_node_repo.sh "{{ my_home }}/nodesource_setup.sh" "{{ node_version }}" "{{ my_user }}"
        args:
          creates: "{{ my_home }}/nodesource_setup.sh"
      - name: Deploy app
        script: ./deploy.sh {{ git_home }} "{{ root_dir }}/{{ app_name }}" "{{ git_repo }}" "{{ my_user }}"
      # args:
      #   creates: /the/created/file.txt
